### ISSUE TITLE
mac 能用吗？

### ISSUE THREAD

**Issue by cyclestudy** [MrXnneHang/Auto_Caption_Generated_Offline#4]
具体怎么操作

**Comment by MrXnneHang** [comment]
mac我这边没有准备好一键包。  

## 环境:
需要自己部署python环境，如果没有经验的话，可以看看miniconda或者anaconda mac是否支持以及基本的用法。  
然后创建一个虚拟环境，  
在pytorch官网找到mac安装torch的方法:[https://pytorch.org/](https://pytorch.org/)  
这里我看官网是这样的，但这么安装只支持cpu推理。我也不清楚mac怎么cuda加速。  
```cmd
python -m pip install torch torchvision torchaudio
```
然后再安装funasr应该就可以  
```cmd
python -m pip install -U funasr
```

我再去导出一个requirements.txt。  
你到时候安装完上面的后  
```cmd
python -m pip installl -r  requirements.txt
```
应该环境上就ok了。

## 推理用的模型:
在modelscope上面下载我写在config.yml中的三个模型。  
文件夹单独放在./models下面即可。  
## 运行：
执行python run_srt.py就可以。  
如果有再报其他错误可以找我 。

**Comment by MrXnneHang** [comment]
模型下载:[https://github.com/MrXnneHang/Auto_Caption_Generated_Offline/blob/master/models/download.md](https://github.com/MrXnneHang/Auto_Caption_Generated_Offline/blob/master/models/download.md)

**Comment by cyclestudy** [comment]
> mac我这边没有准备好一键包。
> 
> ## 环境:
> 需要自己部署python环境，如果没有经验的话，可以看看miniconda或者anaconda mac是否支持以及基本的用法。 然后创建一个虚拟环境， 在pytorch官网找到mac安装torch的方法:https://pytorch.org/ 这里我看官网是这样的，但这么安装只支持cpu推理。我也不清楚mac怎么cuda加速。
> 
> ```batchfile
> python -m pip install torch torchvision torchaudio
> ```
> 
> 然后再安装funasr应该就可以
> 
> ```batchfile
> python -m pip install -U funasr
> ```
> 
> 我再去导出一个requirements.txt。 你到时候安装完上面的后
> 
> ```batchfile
> python -m pip install -r  requirements.txt
> ```
> 
> 应该环境上就ok了。
> 
> ## 推理用的模型:
> 在modelscope上面下载我写在config.yml中的三个模型。 文件夹单独放在./models下面即可。
> 
> ## 运行：
> 执行python run_srt.py就可以。 如果有再报其他错误可以找我 。

始语音识别
You are using the latest version of funasr-1.1.0
  0%|                                                                                               | 0/1 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/Users/oo/soft/Auto_Caption_Generated_Offline/run_srt.py", line 62, in <module>
    main(wav_name=file_names[i].split(".")[0])
  File "/Users/oo/soft/Auto_Caption_Generated_Offline/run_srt.py", line 22, in main
    response = write_long_txt_with_timestamp(wav_name=wav_name, cut_line=cut_line, hot_word=hot_words)  # ./tmp/.txt
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oo/soft/Auto_Caption_Generated_Offline/time_stamp.py", line 11, in write_long_txt_with_timestamp
    model = Model.full_version()
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/oo/soft/Auto_Caption_Generated_Offline/util.py", line 31, in full_version
    funasr_model = AutoModel(
                   ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 229, in build_model
    load_pretrained_model(
  File "/opt/homebrew/lib/python3.11/site-packages/funasr/train_utils/load_pretrained_model.py", line 38, in load_pretrained_model
    src_state = torch.load(path, map_location=map_location)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by cyclestudy** [comment]
<img width="1022" alt="image" src="https://github.com/MrXnneHang/Auto_Caption_Generated_Offline/assets/115349959/5aca99b0-604b-4a5e-b775-da443b99a318">

**Comment by MrXnneHang** [comment]
以及./models下方的文件夹命名和config.yml中是否一致。
